### ISSUE TITLE
Several questions of using meta-model

### ISSUE THREAD

**Issue by cecile-ff** [YujiaBao/Distributional-Signatures#3]
Hi,
I am a user who is quite interested in your few-shot learning algorithm, and it achieves 83% on our Chinese text classification dataset. But in order to apply your algorithm in our dialogue system pipeline, I would like to make sure several points:
1. For train, validation and test dataset, 1 example for support, 25 examples for query? Does it happen that one example being chosen by different episode?
2. After getting a meta-model after training, why you would like to validate with another set of classes? I mean the direct way is to train with the classes you want and also evaluate during training time. Can I understand it as: the training size is training data+validation data? For I should estimate how few data is required while maintaining a high accuracy.
Thanks a lot!

**Comment by YujiaBao** [comment]
1. Yes. For each episode during training/testing, we first sample classes randomly, then sample support and query examples randomly.
2. Because in few-shot learning, what we are evaluating is the ability of learning from few examples for unseen tasks. If you test on examples from seen classes, then you are just evaluating the ability of how to perform well on these given tasks.
